apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: mywebapp
    job: node-api
spec:
  ports:
    - name: flask            # ✅ Must match in ServiceMonitor
      port: 80
      protocol: TCP
  type: NodePort             # ✅ OK to leave as NodePort
  selector:
    app: mywebapp            # ✅ Should match your Deployment/Pod labels
