apiVersion: v1
kind: Service
metadata:
  name: kustom-mywebapp-v1
  namespace: dev
  labels:
    app: mywebapp        # ✅ FIXED: matches the ServiceMonitor
    job: node-api
spec:
  selector:
    app: mywebapp
  ports:
    - name: flask
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
