apiVersion: v1
kind: Service
metadata:
  name: kustom-mywebapp-v1        # ✅ Exact name as in base service.yaml
  labels:
    app: mywebapp                 # ✅ FIXED: label now matches ServiceMonitor
    job: node-api
spec:
  selector:
    app: mywebapp
  ports:
    - name: flask
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
