apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mywebapp-servicemonitor
  namespace: dev
  labels:
    release: my-prometheus       # Must match your Prometheus CR label selector
spec:
  selector:
    matchLabels:
      app: mywebapp              # Must match your Service's label
  namespaceSelector:
    matchNames:
      - dev                      # Namespace where your service is deployed
  jobLabel: job
  endpoints:
    - port: flask                # Must match the named port in your Service
      path: /metrics
      scheme: https              # 🔥 Enables HTTPS scraping
      interval: 30s
      scrapeTimeout: 10s
      tlsConfig:
        insecureSkipVerify: true   # 🔥 Skips TLS cert validation (needed here)
